name: Build Docker Image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get Latest Release
              id: get_release
              run: |
                  latest_release=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .name)
                  echo "Latest release: $latest_release"
                  echo "latest_release=$latest_release" >> $GITHUB_ENV

            - name: Login to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push to GitHub Container Registry
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.latest_release }}
                      ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
